# Prometheus Kebo Config
global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 15s

  external_labels:
    monitor: kebo

rule_files:
- "first.rules"
- "recording.rules"

scrape_configs:

- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090

- job_name: zeus
  static_configs:
  - targets:
    - zeus.kebo.io:9100

- job_name: hera
  static_configs:
  - targets:
    - hera.kebo.io:9100

- job_name: blackbox

  scrape_interval: 60s
  metrics_path: /probe
  params:
    module: [http_2xx] # Look for a HTTP 200 response.
  static_configs:
  - targets:
    # Targets to probe
    - www.kebo.io
    - link.kebo.io
    - www.peterbooker.com
    - www.clorith.net
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115  # Blackbox exporter.

alerting:
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - alertmanager:9093